version: '2'

services:

  motion:
    container_name: motion
    build: 
      context: ./motion/
      args:
        IP_LIST: ${IP_LIST}
    ports:
      - "8080:8080"
      - "${FIRST_CAM_PORT}:${LAST_CAM_PORT}"
    volumes:
      - ${FOOTAGE_DIR}:/etc/motion/footage
    restart: always

  nginx:
    container_name: nginx
    build: 
      context: ./nginx/
      args:
        CAMERA_NUMBER: ${CAMERA_NUMBER}
        MOTION_URL: ${MOTION_URL}
        API_PORT: ${API_PORT}
    ports:
      - "80:80"
      - "${API_PORT}:${API_PORT}"
    restart: always

  statuskeeper:
    container_name: status_keeper
    build: 
      context: ./statuskeeper/
      args:
        CAMERA_NUMBER: ${CAMERA_NUMBER}
        MOTION_URL: ${MOTION_URL}
        API_PORT: ${API_PORT}
    volumes:
      - ./statuskeeper/code:/status
    command: "python3 /status/main.py ${CAMERA_NUMBER} ${MOTION_URL} ${API_PORT}"
    restart: always
